safe: true
include: ['.htaccess','css','images','sites']
exclude: ['link-checker-crawled-pages.pstore','ERRORs.txt','Gemfile','Gemfile.lock','Makefile','vendor']
markdown: kramdown
highlighter: rouge
lsi: false
permalink: pretty
plugins:
  - jekyll-redirect-from
  - jekyll-feed
whitelist:
  - jekyll-redirect-from
  - jekyll-feed
feed:
  posts_limit: 40
  collections:
    announce:
      path: '/announce/feed.xml'
    posts:
      path: ''  # Disabled.
collections:
  announce:
    output: true
    permalink: /:collection/:name/
defaults:
  -
    scope:
      path: ""
      type: "announce"
    values:
      layout: "announce"
