safe: true
lsi: false
highlighter: pygments
exclude: ['Makefile','link-checker-crawled-pages.pstore','ERRORs.txt','Gemfile','Gemfile.lock','vendor']
include: ['.htaccess','css','images','sites']
permalink: pretty
