2014:
  Awardee: "Simon Peyton Jones"
  Citation: |
    Simon Peyton Jones has served the programming languages community
    for many years and in many capacities.  In addition to serving on
    the SIGPLAN Executive Committee and on numerous program committees
    for the major SIGPLAN conferences, he has served as both program
    and general chair for ICFP and program chair for POPL, and as
    editor-in-chief of the Journal of Functional Programming,
    published by Cambridge University Press.  His development and
    maintenance of GHC, the Glasgow Haskell Compiler, as well as his
    stewardship of the Haskell 98 standardization effort, have made
    Haskell into both an active research testbed and an
    industrial-strength language for commercial use, as recognized by
    the 2011 SIGPLAN Software Award.  Last but not least, he has
    played a major leadership role in the recent reform of computing
    education in the UK.  He co-founded and serves as chair of
    Computing at School, the group that was primarily responsible for
    the recent reform of the national curriculum; he was a member of
    the Royal Society working group that wrote the influential report
    "Shut down or restart: the way forward for computing in schools";
    and he chaired the group that drafted the new national programme
    of study for Computing.  Simon's investments in UK education are
    inspiring, and will pay dividends for generations to come.

2013:
  Awardee: "Kathleen Fisher"
  Citation: |

    Kathleen Fisher served on the SIGPLAN Executive committee for
    twelve years, from 2001 to 2012, taking on in succession the roles
    of member-at-large, vice-chair, chair, and past chair.  During
    that time she worked tirelessly to promote programming languages
    among researchers and students.  She has served as program chair
    for many major conferences, including ICFP 2004, CUFP 2006,
    FOOL/WOOD 2006-7, OOPSLA and SPLASH 2011.  Kathleen has also
    served on the board of the CRA, co-chaired CRA's Committee on the
    Status of Women, and edited the Journal of Functional Programming.
    She chairs the PLDI steering committee, and will be general chair
    for ICFP 2015.

    When Kathleen sees a problem, she takes action to fix it.  For
    example, seeing that programming languages were being neglected in
    Computer Science curriculum recommendations, she spearheaded an
    influential workshop and community effort that led to an increased
    role for programming languages in the ACM Curriculum, including
    new emphasis on polymorphism, higher-order functions, type
    systems, static analysis, and garbage collection.  Concerned that
    students were not entering programming languages research, she, in
    collaboration with Ron Garcia and Stephanie Weirich, organized and
    secured funding for the first Programming Languages Mentoring
    Workshop, held at POPL in Philadelphia in 2012, and is helping to
    ensure the continuation of this event by serving on its steering
    committee.

    Kathleen's enthusiasm for programming languages, and for life,
    prompted many of today's volunteers to take the first steps toward
    involvement in SIGPLAN affairs.  The Executive Committee misses
    her wit, wisdom and guidance, but feels that she has truly earned
    the 2013 Distinguished Service Award.

2012:
  Awardee: "Jens Palsberg"
  Citation: |

    The 2012 SIGPLAN service award goes to Jens Palsberg, who has led
    or served on an extraordinary number of program committees, mostly
    for SIGPLAN conferences and workshops.  He was program chair of
    X10 '12, POPL '10, co-chair of SAS '09, chair of PDM '09, chair of
    EMSOFT in '08, chair of TACAS '06, chair of MemoCode '06, chair
    SREIS '02, co-chair of PASTE '02, and chair of SAS '00.  He is
    general co-chair for ICESS '12, and previously was general chair
    of ICESS'10, SPIN in '08, POPL in '05, and conference chair for
    LICS in '09. He has been on the committees for almost 100
    conferences and workshops between 1994 and 2013&#8212;an average
    of more than 5 per year over a 19 year period.  Major conferences
    include POPL (3), PLDI (3), OOPSLA (3), ECOOP (11), SAS (7), ICSE
    (2), and EMSOFT(4).

    Jens is the Editor-in-Chief for TOPLAS, having previously served
    as an associate editor.  He is also on the SIGPLAN CACM Research
    Highlights Selection Committee, and on the Information &
    Computation Editorial Board. He was previously secretary/treasurer
    of SIGBED, and while his work in the SIGBED community is not
    directly related to SIGPLAN, he has actively contributed a
    languages-oriented perspective and agenda to that community.

    The high quality of conferences and journals in our field depends
    on diligent service on program committees and by editors.  This
    award is a small way of thanking Jens for the decades of service
    he has given to our community in these vital roles.
